SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN JULY J ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY SUM(H.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3



# -- 코드를 입력하세요

# SELECT F.FLAVOR
# FROM FIRST_HALF F
#     JOIN JULY J
#     ON F.FLAVOR = J.FLAVOR
# GROUP BY F.FLAVOR
# ORDER BY sum(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
# limit 3